services:

  wordpress:
    container_name: wordpress
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ngx_wp
      - wp_db_rd

  db:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wp_db_rd

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 5
     
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    networks:
      - ngx_wp


  redis:
    container_name: redis
    image: redis:alpine
    #команда написана в логах при загрузке 
    command: redis-server redis.conf
    volumes:
      - ./redis/redis.conf:/data/redis.conf
    networks:
      - wp_db_rd

########## мониторинг
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
     - "9100:9100"
    networks:
     - universal
     
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    # ports:
    #   - "9102:9113" 
    networks:
      - ngx_wp
      - universal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor 
    # ports:
    #   - "9101:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - universal

  promtail:
    container_name: promtail
    image: grafana/promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/config.yaml:/etc/promtail/config.yaml
    ports:
      - "9080:9080"
    networks:
      - universal
###############
volumes:
  wordpress:
  db:
  nginx:

networks:
  ngx_wp:
  wp_db_rd:
  universal:
    name: monitoring
