services:

  wordpress:
    container_name: wordpress
    image: wordpress
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ngx_wp
      - wp_db_rd
      - universal

  db:
    container_name: mysql
    image: mysql:8.0
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wp_db_rd
    depends_on:
      - promtail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 5
     
  nginx:
    container_name: nginx
    image: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - ngx_wp


  redis:
    container_name: redis
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    #команда написана в логах при загрузке 
    command: redis-server redis.conf
    volumes:
      - ./redis/redis.conf:/data/redis.conf
    networks:
      - wp_db_rd
    depends_on:
      - promtail

########## мониторинг
  node-exporter:
    image: prom/node-exporter
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
     - universal
    depends_on:
      - promtail

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor 
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    # ports:
    #   - "9101:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - universal
    depends_on:
      - promtail

  promtail:
    container_name: promtail
    image: grafana/promtail
    logging:
      driver: "json-file"
      options:
        max-size: "${MAX_SIZE_LOG}"
        max-file: "${MAX_FILE_LOG}"
        tag: "{{.Name}}|{{.ImageName}}"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/config.yaml:/etc/promtail/config.yaml
    command:
      - '-config.file=/etc/promtail/config.yaml'
    ports:
      - "9080:9080"
    networks:
      - universal
  
  keycloak-postgres:
    image: library/postgres
    container_name: postgres
    restart: on-failure
    #volumes:
    #  - keycloak-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - universal

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8282:8080
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    # volumes:
    #   - type: bind
    #     source: ./keycloak/client1.json
    #     target: /opt/keycloak/data/import/realm-export.json
    #     read_only: true
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    networks:
      - universal
###############
volumes:
  wordpress:
  db:
  nginx:
  keycloak-postgres:

networks:
  ngx_wp:
  wp_db_rd:
  universal:
    name: monitor