version: '3.1'

services:
#############
  wordpress:
    container_name: wordpress
    image: wordpress
    #restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress/:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ngx_wp
      - wp_db_rd
################
  db:
    container_name: mysql
    image: mysql:8.0
    #restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wp_db_rd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 5
#################      
  nginx:
    container_name: nginx
    image: nginx
    #restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - ngx_wp
###############
  redis:
    container_name: redis
    image: redis:alpine
    #restart: always
    ports:
      - "6379:6379"
    networks:
      - wp_db_rd


###############
volumes:
  wordpress:
  db:
  nginx:

networks:
  ngx_wp:
  wp_db_rd: