services:

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
    volumes:
      - wordpress:/var/www/html
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    command: >
      /bin/sh -c "
      docker-entrypoint.sh apache2-foreground & 
      sleep 7 && 
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && 
      chmod +x wp-cli.phar && 
      mv wp-cli.phar /usr/local/bin/wp && 
      wp core install --url=localhost --title=\"${WP_TITLE}\" --admin_user=${WP_ADMIN_USER} --admin_password=\"${WP_ADMIN_PASSWORD}\" --admin_email=test@test.com --allow-root && 
      echo 'Установка плагина Redis...' && 
      wp plugin install redis-cache --activate --allow-root && 
      echo 'Включение Redis...' && 
      wp redis enable --allow-root && 
      echo 'Настройка завершена!' && 
      wait
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ngx_wp
      - wp_db_rd
      - universal

  db:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wp_db_rd
      - universal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 5
     
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    networks:
      - ngx_wp
      - universal

  redis:
    container_name: redis
    image: redis:alpine
    #команда написана в логах при загрузке 
    command: redis-server redis.conf
    volumes:
      - ./redis/redis.conf:/data/redis.conf
    networks:
      - wp_db_rd
      - universal
########## мониторинг
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
     - "9100:9100"
    networks:
     - universal
     
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    ports:
      - "9113:9113" 
    environment:
      - NGINX_SCRAPE_URI=http://localhost/nginx_status
    networks:
      - universal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor 
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - universal

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./prometheus/data:/prometheus/data
    ports:
      - "9090:9090"
    networks:
      - universal
    depends_on:
      - nginx
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
     - universal
    depends_on:
      - nginx
###############
volumes:
  wordpress:
  db:
  nginx:

networks:
  ngx_wp:
  wp_db_rd:
  universal: