# prometheus/prometheus.yml

global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']



  # - job_name: 'nik_cadvisor'
  #   static_configs:
  #     - targets: ['192.168.4.131:8080']
  
  # - job_name: 'nik_node-exporter'
  #   static_configs:
  #     - targets: ['192.168.4.131:9100']
  
      